name: pappap_mobile_wallet
description: Official Pappap AI Chain SNN Mobile Wallet - Made in Vietnam
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.4
  animate_do: ^3.3.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
